---
title: "**Informatie2**"
output: 
  html_document:
    toc: false
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
---
<br>  
  

  
  
## voor deelname aan het wetenschappelijke onderzoek: 
## *De impact van sport apps*
  

----

<br>

# **1a. Introductie**
Dit onderzoek wordt uitgevoerd door de afdelingen Sociologie en Orthopedagogiek: Leren en Ontwikkeling van de Radboud Universiteit, met onderzoeksleiders Rob Franken, dr. Hidde Bekhuis en prof. dr. Jochem Tolsma. Het doel van dit onderzoek is om inzicht te krijgen de mechanismen via welke (online) sociale netwerken sport gedrag kunnen motiveren.

<br>

# **1b. Het onderzoek**
Een actieve leefstijl heeft veel voordelen. Nagenoeg alle huidige initatieven gericht op het bevorderen van een actieve leefstijl richten zich op het actief krijgen van mensen. Bovendien kent de huidige werkwijze een veelal persoonsgerichte benadering. Echter, tot op heden is er relatief weinig oog voor de rol van de sociale context. Naar verwachting is het juist de sociale context die van belang is voor het motiveren van een duurzame actieve leefstijl. Van alle sociale en omgevingsfactoren die van invloed zijn op fysieke activiteit, vormen sociale netwerken het meest prominente doel voor interventies en programma's gericht op het promoten van een actieve leefstijl. Met name online sociale netwerken zijn een zeer aantrekkelijk doelwit geworden voor grootschalige gezondheidsinitiatieven. Echter, tot op heden is er onvoldoende kennis over waarom deze online netwerken effectieve bronnen van sociale invloed zijn voor het verbeteren van fysieke activiteit. 

Jij start met een cursus Krachttraining bij het Radboud Sportcentrum. We willen je vragen om gedurende deze cursus gebruik te maken van een sport app, te weten [STRAVA](https://www.strava.com/) of [STRONG](https://www.strong.app/). We vragen je om je trainingsactiviteiten bij te houden, in een virtueel logboek. Daarnaast heb je de kans dat je in een online netwerk wordt geplaats (in Strava), samen met 5 andere deelnemers aan de cursus. Als je in een online sociaal netwerk geplaats wordt, zul je de trainingsactiviteiten/logboeken van je teamgenoten te zien krijgen. Daarnaast heb je de kans dat jullie activiteiten worden bijgehouden in een klassement/ranking, of dat jullie elkaar virtuele duimpjes/'kudos' kunnen geven.   

<!--- 

Jullie zullen anonieme accounts gebruiken: er valt dus niet te herleiden wie jij en je 'teamgenoten' zijn.

---> 

Voordat je begint met het bijhouden van het logboek, vragen we je om een korte (online) vragenlijst in te vullen. Hierin vragen we je onder andere naar je voorgaande ervaring met sport apps, naar je trainingsverleden, en je huidige motivaties om te sporten/trainen.

Na afloop van de cursus leggen we je graag nogmaals een korte vragenlijst voor, waarin we je vragen om het gebruik van de app, en (indien van toepassing) het online netwerk, te evalueren. 

We houden je graag op de hoogte van ons onderzoek. Voor meer informatie, alsmede de uiteindelijke resultaten, zie onze Open Science Framework (OSF) pagina: [(link)](https://osf.io/).

Dit onderzoek is onafhankelijk getoetst door de Ethiek Commissie Sociale Wetenschappen (ECSW) van de Radboud Universiteit, en er is formeel geen bezwaar tegen dit onderzoek.

<br>

# **2a. Gebruik van je persoonsgegevens**
Voor het huidige onderzoek is het nodig om de over jouw verzamelde gegevens door het Radboud Sport Centrum (RSC) te gebruiken. Het gaat daarbij om het aantal ticketuren, cursussen en fitnessbezoeken. Verder is het nodig dat je persoonsgegevens worden verzameld en gebruikt. Het gaat om je e-mailadres en je studenten- (S-) nummer. Deze gegevens worden gebruikt om jouw vragenlijstgegevens te koppelen aan de RSC-gegevens, en om je te kunnen benaderen voor verdere vragenlijsten tijdens dit onderzoek.
In het toestemmingsformulier word je gevraagd om toestemming te geven voor het verzamelen, gebruiken en bewaren van bovengenoemde gegevens. Als je hier niet mee instemt, kun je niet deelnemen aan het onderzoek.

<br>

# **2b. Vertrouwelijkheid van je gegevens en gegevensverwerking**
De informatie die je verstrekt ten behoeve van het onderzoek wordt zorgvuldig behandeld en is alleen toegankelijk voor de onderzoeksleiders. Persoonsgegevens die wij tijdens het onderzoek over je verzamelen, blijven vertrouwelijk. Om je privacy te waarborgen slaan we je persoonsgegevens gecodeerd/gepseudonimiseerd op. Dat betekent dat je naam en andere gegevens die jou direct kunnen identificeren apart van de onderzoeksgegevens worden bewaard. Alleen middels een code of proefpersoonnummer is te achterhalen welke onderzoeksgegevens bij welke persoon horen. De link tussen gegevens die jou direct kunnen identificeren en de overige onderzoeksgegevens wordt opgeslagen in een geëncrypt sleutelbestand. Alleen de onderzoeksleiders hebben toegang tot deze informatie. Ook in rapporten en publicaties over het onderzoek worden alleen je geanonimiseerde onderzoeksgegevens vermeld.

<br>

# **2c. Bewaartermijn van je gegevens**
Het door jou ondertekende toestemmingsformulier wordt gedurende 2 jaar na afronding van het onderzoek bewaard. Je (beschermde) persoons-/onderzoeksgegevens worden gedurende de loop van het onderzoek (2 jaar) bewaard. Je kunt te allen tijde, gedurende de looptermijn van het onderzoek, je toestemming om persoonlijke data te verwerken, intrekken, zonder opgaaf van redenen. Neem hiervoor contact op met de onderzoeksleiders (rob.franken@ru.nl). Dan zullen we de gegevens die je reeds hebt verstrekt verwijderen.

<br>

# **2c. Delen van je gegevens**
Vanwege het belang van controle, hergebruik en/of replicatie van onderzoeksresultaten worden onderzoeksgegevens (inclusief eventuele anonieme persoonsgegevens) in toenemende mate gedeeld met of openbaar gemaakt voor andere onderzoekers. Voorafgaand aan deze vorm van delen worden jouw gegevens geanonimiseerd. Dit betekent dat je niet (meer) te identificeren bent op basis van de gegevens. Een geanonimiseerde versie van de gegevens uit dit onderzoek zal na 2 jaar openbaar gemaakt worden via [DANS EASY](https://easy.dans.knaw.nl/ui/home). Indien je niet wenst dat jouw geanonimiseerde gegevens gedeeld worden, kun je maximaal 1 maand na afronding van het onderzoek verzoeken jouw gegevens te laten verwijderen. Nadat we een geanonimiseerde versie van de gegevens uit dit onderzoek openbaar hebben gemaakt, zullen we al je persoonlijke gegevens die tot jouw identiteit kunnen leiden definitief verwijderen. Nadat de anonieme dataset openbaar is gemaakt, is het niet meer mogelijk om data te verwijderen, aangezien deze alleen nog anoniem bewaard blijven. Wij weten dan dus niet meer welke onderzoeksgegevens bij jou horen.

<br>

# **3. Toekomstig onderzoek**
Na deelname aan het onderzoek zouden wij je graag willen benaderen voor toekomstig onderzoek. Je kunt op het toestemmingsformulier aangeven of je hiermee akkoord bent. Indien je hiermee instemt word je e-mailadres bewaard voor maximaal 2 jaar. Ook voor dit toekomstige onderzoek geldt dat deelname altijd vrijwillig is en dat voor je eventuele deelname aan een nieuw onderzoek altijd opnieuw om je toestemming gevraagd wordt. Je kunt op elk gewenst moment je contactgegevens laten verwijderen en/of de toestemming om benaderd te kunnen worden voor toekomstig onderzoek intrekken.

<br>

# **4. Vrijwillige deelname**
Je deelname aan dit onderzoek is geheel vrijwillig. Als je besluit om niet deel te nemen aan dit onderzoek heeft dit geen nadelige gevolgen voor je. Ook tijdens het onderzoek heb je altijd het recht om je toestemming in te trekken en je deelname te beëindigen. Ook dit heeft geen nadelige gevolgen.

<br>

# **5. Vergoeding of opbrengst**
Je deelname aan dit onderzoek wordt erg op prijs gesteld. De kennis die we vergaren op basis van jouw deelname helpt het Radboud Sportcentrum en andere organisaties om interventies of programma’s te ontwikkelen waarmee een actieve leefstijl na de overgang naar de universiteit kan worden gepromoot. Om je te bedanken voor je deelname, krijg je eenmaals een start-vergoeding van €5,- (na het invullen van de eerste vragenlijst), en nogmaals €5,- als je het logboek goed hebt bijgehouden gedurende de cursus. Daarnaast heb je een kans om een geldprijs van €10,- te winnen, als je de challenge/opdracht voltooid (hierover hoor je meer als je de vragenlijst hebt ingevuld).

<br>

# **6. Contactinformatie **
Bij vragen, opmerkingen of zorgen over deze studie, kun je contact opnemen met de verantwoordelijke onderzoeker: Rob Franken (Radboud Universiteit Nijmegen, afdeling Sociologie; rob.franken@ru.nl).

<br> 

# **7. Afsluiting **
Met sportieve groet,

<br>

Rob Franken

Dr. Hidde Bekhuis

Prof. dr. Jochem Tolsma

<br>

----

----

<br>

# **TOESTEMMINGSVERKLARING**

voor deelname aan het wetenschappelijke onderzoek: 
*De impact van sport apps* 

**Ik bevestig dat**:

- ik schriftelijk naar tevredenheid over het onderzoek geïnformeerd ben;

- ik de schriftelijke informatie goed heb gelezen;

- ik in de gelegenheid ben gesteld om vragen over het onderzoek te stellen;

- mijn eventuele vragen naar tevredenheid zijn beantwoord;

- ik goed over deelname aan het onderzoek heb kunnen nadenken;

- ik uit vrije wil deelneem aan het onderzoek.

**Ik begrijp dat**:

- ik het recht heb om mijn toestemming op ieder moment weer in te trekken zonder opgave van redenen en zonder dat dit nadelige gevolgen voor mij heeft, door contact op te nemen met Rob Franken via rob.franken@ru.nl;

- ik het recht heb op vernietiging van mijn onderzoeksgegevens tot 1 maand na afronding van het onderzoek;

- ik het recht heb om mijn toestemming voor de (verdere) verwerking van mijn persoonsgegevens in te trekken; mijn persoonsgegevens worden verwerkt volgens de geldende Europese privacyregelgeving;
- mijn persoonsgegevens worden verwerkt volgens de [privacyverklaring](https://www.ru.nl/vaste-onderdelen/privacyverklaring-radboud-universiteit) van de Radboud Universiteit ;

**Ik stem in dat**:

- mijn persoons- en/of onderzoeksgegevens binnen dit onderzoek voor wetenschappelijke doelen worden verkregen en gedurende 2 jaar beschikbaar zullen zijn voor controle, hergebruik en replicatie;

- het ondertekende toestemmingsformulier met mijn persoonsgegevens gedurende 2 jaar wordt bewaard;

- mijn persoonsgegevens welke uitsluitend voor administratieve doelen worden verkregen tot maximaal 1 maand na afronding van het onderzoek worden bewaard. Administratieve doelen houden onder meer in: om je te kunnen uitnodigen voor vragenlijst tijdens dit onderzoek;

- voor de controle van het onderzoek toezichthoudende autoriteiten mijn persoons- en onderzoeksgegevens kunnen inzien.

**Daarnaast geef ik ook toestemming**:

- voor het verwerken van de volgende (bijzondere) persoonsgegevens over mij:
De door het Radboud Sportcentrum (RSC) verzamelde data, over het aantal fitnessbezoeken, ticketuren, en cursussen.

