---
title: "**Informatiebrief**"
output: 
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
---
<br>  
  


## voor deelname aan het wetenschappelijke onderzoek: *Actieve leefstijlen onder studenten*


----

<br>

# **1a. Introductie**
Dit onderzoek wordt uitgevoerd door de afdelingen Sociologie en Orthopedagogiek: Leren en Ontwikkeling van de Radboud Universiteit, met onderzoeksleiders Rob Franken, dr. Hidde Bekhuis en prof. dr. Jochem Tolsma. Het doel van dit onderzoek is om inzicht te krijgen in de rol van het sociale netwerk van een individu in diens actieve leefstijl nadat hij/zij de transitie naar de universiteit heeft gemaakt.

<br>

# **1b. Het onderzoek**
Een actieve leefstijl heeft veel voordelen. Helaas zien we dat de overgang naar de universiteit 
vaak een (blijvend) negatieve invloed heeft op fysieke activiteit. De transitie naar de 
universiteit gaat gepaard met een nieuwe studieomgeving, vaak een nieuwe woonomgeving, nieuwe 
verantwoordelijkheden, en een veranderend sociaal netwerk. Met ons onderzoek willen de kennis 
vergroten over hoe en waarom deze veranderingen gepaard gaan met veranderingen in sportdeelname.

Jij start dit jaar met een studie aan de Radboud Universiteit en je hebt je ingeschreven bij het 
sportcentrum. We willen je over de tijd enkele online vragenlijsten voorleggen. Daarin zijn we 
voornamelijk geïnteresseerd in (1) je sport-en-beweeg gedrag, zowel voor als na de overgang naar de 
universiteit, en (2) je sociale netwerk, alsmede veranderingen daarin over de tijd (bijv., wie zijn 
de mensen met wie je sport, je belangrijke studiegenoten, en belangrijk(st)e vrienden?).

We willen je in het begin van het jaar (in september) een basisvragenlijst voorleggen waarin we 
belangrijke achtergrondinformatie verzamelen. We nemen je terug naar de tijd voor de universiteit, 
en vragen je naar je sportdeelname in die tijd. Bijvoorbeeld: Sportte je tijdens de middelbare 
school, en zo ja, hoe vaak, en in welk verband (bijvoorbeeld als lid van een club)? Verder zijn we 
benieuwd naar belangrijke veranderingen tijdens je overgang naar de universiteit, bijvoorbeeld: Ben 
je verhuisd, en zo ja, wat is je huidige woonsituatie? Een aantal weken daarna, willen we je 
nogmaals een online vragenlijst voorleggen waarin we ingaan op je sociale netwerk. We vragen je wie 
de belangrijkste mensen zijn met wie je belangrijke zaken bespreekt, met wie je studeert, 
afspreekt, en samen sport. We willen je nogmaals een soortgelijke vragenlijst voorleggen rond 
februari en juli 2022, met als doel om te kijken in hoeverre deze netwerken aan verandering
onderhevig zijn. Als je daarvoor toestemming geeft, zouden we in het collegejaar 2022-2013 nogmaals drie korte vergelijkbare vragenlijsten willen voorleggen.

We houden je graag op de hoogte van ons onderzoek. Voor meer informatie, alsmede de uiteindelijke resultaten, zie onze Open Science Framework (OSF) pagina: [(link)](https://osf.io/).

Dit onderzoek is onafhankelijk getoetst door de Ethiek Commissie Sociale Wetenschappen (ECSW) van de Radboud Universiteit, en er is formeel geen bezwaar tegen dit onderzoek.

<br>

# **2a. Gebruik van je persoonsgegevens**
Voor het huidige onderzoek is het nodig om de over jouw verzamelde gegevens door het Radboud Sport Centrum (RSC) te gebruiken. Het gaat daarbij om het aantal ticketuren, cursussen en fitnessbezoeken. Verder is het nodig dat je persoonsgegevens worden verzameld en gebruikt. Het gaat om je e-mailadres en je studenten- (S-) nummer. Deze gegevens worden gebruikt om jouw vragenlijstgegevens te koppelen aan de RSC-gegevens, en om je te kunnen benaderen voor verdere vragenlijsten tijdens dit onderzoek.
In het toestemmingsformulier word je gevraagd om toestemming te geven voor het verzamelen, gebruiken en bewaren van bovengenoemde gegevens. Als je hier niet mee instemt, kun je niet deelnemen aan het onderzoek.

<br>

# **2b. Vertrouwelijkheid van je gegevens en gegevensverwerking**
De informatie die je verstrekt ten behoeve van het onderzoek wordt zorgvuldig behandeld en is alleen toegankelijk voor de onderzoeksleiders. Persoonsgegevens die wij tijdens het onderzoek over je verzamelen, blijven vertrouwelijk. Om je privacy te waarborgen slaan we je persoonsgegevens gecodeerd/gepseudonimiseerd op. Dat betekent dat je naam en andere gegevens die jou direct kunnen identificeren apart van de onderzoeksgegevens worden bewaard. Alleen middels een code of proefpersoonnummer is te achterhalen welke onderzoeksgegevens bij welke persoon horen. De link tussen gegevens die jou direct kunnen identificeren en de overige onderzoeksgegevens wordt opgeslagen in een geëncrypt sleutelbestand. Alleen de onderzoeksleiders hebben toegang tot deze informatie. Ook in rapporten en publicaties over het onderzoek worden alleen je geanonimiseerde onderzoeksgegevens vermeld.

<br>

# **2c. Bewaartermijn van je gegevens**
Het door jou ondertekende toestemmingsformulier wordt gedurende 2 jaar na afronding van het onderzoek bewaard. Je (beschermde) persoons-/onderzoeksgegevens worden gedurende de loop van het onderzoek (2 jaar) bewaard. Je kunt te allen tijde, gedurende de looptermijn van het onderzoek, je toestemming om persoonlijke data te verwerken, intrekken, zonder opgaaf van redenen. Neem hiervoor contact op met de onderzoeksleiders (rob.franken@ru.nl). Dan zullen we de gegevens die je reeds hebt verstrekt verwijderen.

<br>

# **2c. Delen van je gegevens**
Vanwege het belang van controle, hergebruik en/of replicatie van onderzoeksresultaten worden onderzoeksgegevens (inclusief eventuele anonieme persoonsgegevens) in toenemende mate gedeeld met of openbaar gemaakt voor andere onderzoekers. Voorafgaand aan deze vorm van delen worden jouw gegevens geanonimiseerd. Dit betekent dat je niet (meer) te identificeren bent op basis van de gegevens. Een geanonimiseerde versie van de gegevens uit dit onderzoek zal na 2 jaar openbaar gemaakt worden via [DANS EASY](https://easy.dans.knaw.nl/ui/home). Indien je niet wenst dat jouw geanonimiseerde gegevens gedeeld worden, kun je maximaal 1 maand na afronding van het onderzoek verzoeken jouw gegevens te laten verwijderen. Nadat we een geanonimiseerde versie van de gegevens uit dit onderzoek openbaar hebben gemaakt, zullen we al je persoonlijke gegevens die tot jouw identiteit kunnen leiden definitief verwijderen. Nadat de anonieme dataset openbaar is gemaakt, is het niet meer mogelijk om data te verwijderen, aangezien deze alleen nog anoniem bewaard blijven. Wij weten dan dus niet meer welke onderzoeksgegevens bij jou horen.

<br>

# **3. Toekomstig onderzoek**
Na deelname aan het onderzoek zouden wij je graag willen benaderen voor toekomstig onderzoek. Je kunt op het toestemmingsformulier aangeven of je hiermee akkoord bent. Indien je hiermee instemt word je e-mailadres bewaard voor maximaal 2 jaar. Ook voor dit toekomstige onderzoek geldt dat deelname altijd vrijwillig is en dat voor je eventuele deelname aan een nieuw onderzoek altijd opnieuw om je toestemming gevraagd wordt. Je kunt op elk gewenst moment je contactgegevens laten verwijderen en/of de toestemming om benaderd te kunnen worden voor toekomstig onderzoek intrekken.

<br>

# **4. Vrijwillige deelname**
Je deelname aan dit onderzoek is geheel vrijwillig. Als je besluit om niet deel te nemen aan dit onderzoek heeft dit geen nadelige gevolgen voor je. Ook tijdens het onderzoek heb je altijd het recht om je toestemming in te trekken en je deelname te beëindigen. Ook dit heeft geen nadelige gevolgen.

<br>

# **5. Vergoeding of opbrengst**
Je deelname aan dit onderzoek wordt erg op prijs gesteld. De kennis die we vergaren op basis van jouw deelname helpt het Radboud Sportcentrum en andere organisaties om interventies of programma’s te ontwikkelen waarmee een actieve leefstijl na de overgang naar de universiteit kan worden gepromoot. Om deelnemers te bedanken, verloten we 1x een iPad Pro (t.w.v. €899,-) en 25x een jaarabonnement bij het Radboud Sportcentrum (t.w.v. €123,-). De loterij is na afloop van het collegejaar (augustus 2022). Het aantal online vragenlijsten dat je invult staat gelijk aan het aantal keer dat je naam voorkomt in de loterij. Met andere woorden, je win-kans wordt vergroot door vaker vragenlijsten in te vullen.

<br>

# **6. Contactinformatie **
Bij vragen, opmerkingen of zorgen over deze studie, kun je contact opnemen met de verantwoordelijke onderzoeker: Rob Franken (Radboud Universiteit Nijmegen, afdeling Sociologie; rob.franken@ru.nl).

<br> 

# **7. Afsluiting **
Met sportieve groet,

<br>

Rob Franken

Dr. Hidde Bekhuis

Prof. dr. Jochem Tolsma

<br>

----

----

<br>

# **TOESTEMMINGSVERKLARING**

voor deelname aan het wetenschappelijke onderzoek: 
*Actieve leefstijlen onder studenten* 

**Ik bevestig dat**:

- ik schriftelijk naar tevredenheid over het onderzoek geïnformeerd ben;

- ik de schriftelijke informatie goed heb gelezen;

- ik in de gelegenheid ben gesteld om vragen over het onderzoek te stellen;

- mijn eventuele vragen naar tevredenheid zijn beantwoord;

- ik goed over deelname aan het onderzoek heb kunnen nadenken;

- ik uit vrije wil deelneem aan het onderzoek.
Ik begrijp dat:

- ik het recht heb om mijn toestemming op ieder moment weer in te trekken zonder opgave van redenen en zonder dat dit nadelige gevolgen voor mij heeft, door contact op te nemen met Rob Franken via rob.franken@ru.nl;

- ik het recht heb op vernietiging van mijn onderzoeksgegevens tot 1 maand na afronding van het onderzoek;

- ik het recht heb om mijn toestemming voor de (verdere) verwerking van mijn persoonsgegevens in te trekken; mijn persoonsgegevens worden verwerkt volgens de geldende Europese privacyregelgeving;
- mijn persoonsgegevens worden verwerkt volgens de [privacyverklaring](https://www.ru.nl/vaste-onderdelen/privacyverklaring-radboud-universiteit) van de Radboud Universiteit ;

**Ik stem in dat**:

- mijn persoons- en/of onderzoeksgegevens binnen dit onderzoek voor wetenschappelijke doelen worden verkregen en gedurende 2 jaar beschikbaar zullen zijn voor controle, hergebruik en replicatie;

- het ondertekende toestemmingsformulier met mijn persoonsgegevens gedurende 2 jaar wordt bewaard;

- mijn persoonsgegevens welke uitsluitend voor administratieve doelen worden verkregen tot maximaal 1 maand na afronding van het onderzoek worden bewaard. Administratieve doelen houden onder meer in: om je te kunnen uitnodigen voor vragenlijst tijdens dit onderzoek;

- voor de controle van het onderzoek toezichthoudende autoriteiten mijn persoons- en onderzoeksgegevens kunnen inzien.

**Daarnaast geef ik ook toestemming**:

- voor het verwerken van de volgende (bijzondere) persoonsgegevens over mij:
De door het Radboud Sportcentrum (RSC) verzamelde data, over het aantal fitnessbezoeken, ticketuren, en cursussen.

